<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
	<LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.1.0-pre02" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yes.Domain\Yes.Domain.csproj" />
    <ProjectReference Include="..\Yes.Shared\Yes.Shared.csproj" />
  </ItemGroup>

</Project>
