// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yes.Infrastructure;

#nullable disable

namespace Yes.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260829134739_TaskDescriptionIsOptionalMigration")]
partial class _20260829134739_TaskDescriptionIsOptionalMigration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.7.26381.103")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Yes.Domain.Entities.TaskEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<Guid>("ToDoListId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("ToDoListId");

                b.ToTable("Tasks");
            });

        modelBuilder.Entity("Yes.Domain.Entities.ToDoListEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("ToDoLists");
            });

        modelBuilder.Entity("Yes.Domain.Entities.UserEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("Yes.Domain.Entities.TaskEntity", b =>
            {
                b.HasOne("Yes.Domain.Entities.ToDoListEntity", "ToDoList")
                    .WithMany("Tasks")
                    .HasForeignKey("ToDoListId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ToDoList");
            });

        modelBuilder.Entity("Yes.Domain.Entities.ToDoListEntity", b =>
            {
                b.HasOne("Yes.Domain.Entities.UserEntity", "User")
                    .WithMany("ToDoLists")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Yes.Domain.Entities.ToDoListEntity", b =>
            {
                b.Navigation("Tasks");
            });

        modelBuilder.Entity("Yes.Domain.Entities.UserEntity", b =>
            {
                b.Navigation("ToDoLists");
            });
#pragma warning restore 612, 618
    }
}
