@Yes.WebApi_HostAddress = http://localhost:5200
@Yes.WepApi_UserId = empty
@Yes.WebApi_ToDoListId = empty
@Yes.WebApi_TaskId = empty

### AddUser
POST {{Yes.WebApi_HostAddress}}/api/users
Content-Type: application/json
Accept: application/json
{
  "username": "Tester",
  "email": "tester@example.com",
  "password": "tester123"
}

### GetUserById
GET {{Yes.WebApi_HostAddress}}/api/users/{{Yes.WepApi_UserId}}
Accept: application/json

### UpdateUserById
PUT {{Yes.WebApi_HostAddress}}/api/users/{{Yes.WepApi_UserId}}
Content-Type: application/json
Accept: application/json
{
  "username": "RealUser",
  "email": "realuser@example.com",
  "password": "realuser123"
}

### DeleteUserById
DELETE {{Yes.WebApi_HostAddress}}/api/users/{{Yes.WepApi_UserId}}

### AddToDoList
POST {{Yes.WebApi_HostAddress}}/api/todo-lists
Content-Type: application/json
Accept: application/json
{
  "name": "My ToDo List",
  "userId": "{{Yes.WepApi_UserId}}"
}

### GetToDoListById
GET {{Yes.WebApi_HostAddress}}/api/todo-lists/{{Yes.WebApi_ToDoListId}}
Accept: application/json

### UpdateToDoListById
PUT {{Yes.WebApi_HostAddress}}/api/todo-lists/{{Yes.WebApi_ToDoListId}}
Content-Type: application/json
Accept: application/json
{
  "name": "Updated ToDo List"
}

### DeleteToDoListById
DELETE {{Yes.WebApi_HostAddress}}/api/todo-lists/{{Yes.WebApi_ToDoListId}}
Accept: application/json

### AddTask
POST {{Yes.WebApi_HostAddress}}/api/tasks
Content-Type: application/json
Accept: application/json
{
  "name": "Buy an apple",
  "toDoListId": "{{Yes.WebApi_ToDoListId}}"
}

### GetTaskById
GET {{Yes.WebApi_HostAddress}}/api/tasks/{{Yes.WebApi_TaskId}}
Accept: application/json

### UpdateTaskById
PUT {{Yes.WebApi_HostAddress}}/api/tasks/{{Yes.WebApi_TaskId}}
Content-Type: application/json
Accept: application/json
{
  "name": "Buy a green apple",
  "description": "in city market",
  "isCompleted": true
}

### DeleteTaskById
DELETE {{Yes.WebApi_HostAddress}}/api/tasks/{{Yes.WebApi_TaskId}}
Accept: application/json